sonar.projectKey=miksrv_astronomy-portal
sonar.organization=miksoft
sonar.sources=client,server/app
sonar.exclusions=**/*.test.tsx,**/*.test.ts,server/tests/**
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.php.coverage.reportPaths=server/build/logs/clover.xml
sonar.coverage.exclusions=client/jest.config.ts,client/next-sitemap.config.js,client/next.config.js,client/setupTests.config.tsx,client/components/**/index.ts,server/app/Config/**,server/app/Database/**,server/app/Language/**,server/app/Views/**,server/**/index.html
