import Head from 'next/head'
import { Inter } from 'next/font/google'
import {
    useGetCatalogListQuery,
    getCatalogList,
    getCatalogItem,
    getRunningQueriesThunk,
    useGetCatalogItemQuery
} from "@/api/api";
import Link from "next/link";
import {store, wrapper} from "@/api/store";
import { InferGetServerSidePropsType } from 'next'
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import {skipToken} from "@reduxjs/toolkit/query";

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = wrapper.getStaticProps(
    (store) => async (context) => {
        store.dispatch(getCatalogList.initiate());

        await Promise.all(store.dispatch(getRunningQueriesThunk()));

        return {
            props: { object: {} },
        };
    }
);

export default function Home() {
    const { isLoading, error, data } = useGetCatalogListQuery();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                Hello, world!!!
                <ul>
                {data && data.payload.map((item) => (
                    <li key={item.name}>
                        <Link href={`/objects/${item.name}`} title={item.category}>{item.title || item.name}</Link>
                    </li>
                ))}
                </ul>
            </main>
        </>
    )
}
